# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12683014329b041ab139b9c7cd59b30db44be627e64a82fe66d7c521782fee04fa7f2e2c8cd051aad8fe0afa52a114766b11ff93fa3d9d769b86b74909247f01

test:
  secret_key_base: 40bb4c8cf5adeff1e1cf802b18bfcd432de7cd955490785a42e899374d543ab7cbd76f0e32232dfdded4310bb5736e3662822409c546db47b78515d054b5b6f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
